services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: typing_user
      POSTGRES_PASSWORD: typing_pass
      POSTGRES_DB: typing_speed_game
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: